#!/usr/bin/env python3
"""Generate SQL migration 062 from tuned game config overrides.

Usage:
    python generate_migration.py
    python generate_migration.py --config results/config_overrides.json
    python generate_migration.py --config results/config_overrides.json --output db/062_balanced_game_configs.sql
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone


def generate_sql(overrides: dict) -> str:
    """Generate SQL UPDATE statements for changed config values.

    Args:
        overrides: Dict of {config_key: new_value} to apply.

    Returns:
        SQL string with UPDATE statements, or empty string if no overrides.
    """
    if not overrides:
        return "-- No config changes to apply.\n"

    lines = []
    for key in sorted(overrides.keys()):
        value = overrides[key]
        # value_json stores all values as strings in the DB
        if isinstance(value, float):
            str_val = str(value)
        elif isinstance(value, int):
            str_val = str(value)
        else:
            str_val = str(value)
        lines.append(
            f"UPDATE game_configs SET value_json = '{str_val}' WHERE key = '{key}';"
        )

    return "\n".join(lines)


def build_migration(
    overrides: dict,
    output_path: str,
    run_ids: list[str] | None = None,
    description: str = "",
) -> str:
    """Build a complete migration SQL file from config overrides.

    Args:
        overrides: Dict of {config_key: new_value}.
        output_path: Path to write the .sql file.
        run_ids: List of simulation run IDs that informed these values.
        description: Human-readable description of the tuning pass.

    Returns:
        The full SQL content written.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    run_list = ", ".join(run_ids) if run_ids else "none"

    header = f"""-- Migration 062: Balanced Game Configs
-- Generated by simulation toolkit on {now}
-- Based on simulation runs: {run_list}
-- Description: {description or 'Tuned game configs for progression balance'}
--
-- This migration updates game_configs values to hit the 60-hour casual
-- completion target across all player archetypes.
--
-- To apply:
--   psql "$DATABASE_URL" -f db/062_balanced_game_configs.sql

"""
    sql_body = generate_sql(overrides)
    content = header + sql_body + "\n"

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    return content


def build_migration_from_file(
    config_path: str,
    output_path: str,
) -> str:
    """Build migration from a config_overrides.json file.

    The JSON file format:
    {
        "description": "Config v2 — reduced HP scaling",
        "overrides": {
            "hp_scaling_factor": 1.45,
            "gold_to_essence_base_rate": 800
        }
    }
    """
    with open(config_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    overrides = data.get("overrides", {})
    description = data.get("description", "")
    run_ids = data.get("run_ids", [])

    return build_migration(overrides, output_path, run_ids=run_ids, description=description)


def main():
    parser = argparse.ArgumentParser(description="Generate migration 062 from tuned configs")
    parser.add_argument(
        "--config",
        default="results/config_overrides.json",
        help="Path to config overrides JSON (default: results/config_overrides.json)",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output SQL path (default: db/062_balanced_game_configs.sql)",
    )
    args = parser.parse_args()

    # Resolve paths relative to project root
    sim_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(sim_dir, "..", ".."))

    config_path = args.config
    if not os.path.isabs(config_path):
        config_path = os.path.join(sim_dir, config_path)

    output_path = args.output or os.path.join(project_root, "db", "062_balanced_game_configs.sql")

    if not os.path.exists(config_path):
        print(f"Error: Config file not found: {config_path}", file=sys.stderr)
        print("Create results/config_overrides.json first (see spec Section 8.4)", file=sys.stderr)
        sys.exit(1)

    content = build_migration_from_file(config_path, output_path)
    print(f"Migration written to: {output_path}")
    print(f"SQL statements: {content.count('UPDATE')}")


if __name__ == "__main__":
    main()
