-- Migration 062: Balanced Game Configs
-- Generated by simulation toolkit on 2026-03-22 05:57 UTC
-- Based on simulation runs: math_model_run_007, math_model_run_017
-- Description: Config v2 — Slow XP 4x (factor 20->80), fix economy (essence base 500->200, growth 1.03->1.01, upgrade scaling 1.04->1.03). Combat HP already good via scene-based scaling.
--
-- This migration updates game_configs values to hit the 60-hour casual
-- completion target across all player archetypes.
--
-- To apply:
--   psql "$DATABASE_URL" -f db/062_balanced_game_configs.sql

UPDATE game_configs SET value_json = '80' WHERE key = 'char_level_xp_factor';
UPDATE game_configs SET value_json = '200' WHERE key = 'char_xp_per_scene_base';
UPDATE game_configs SET value_json = '200' WHERE key = 'gold_to_essence_base_rate';
UPDATE game_configs SET value_json = '1.01' WHERE key = 'gold_to_essence_growth_factor';
UPDATE game_configs SET value_json = '0.5' WHERE key = 'idle_essence_drain_per_minute';
UPDATE game_configs SET value_json = '1.03' WHERE key = 'upgrade_cost_scaling';
