"""Generate migration 040: Seed music definitions, boss themes, and extended SFX."""

import json
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from generate_8bit_music import generate_all_states, generate_state, ARCHETYPES
from generate_8bit_sfx import generate_preset

lines = []
lines.append("-- Migration 040: Seed music definitions, boss themes, and extended SFX (2.5.4)")
lines.append("-- Generated by tools/generate_migration_040.py")
lines.append("")

# 1. Music definitions for the 13 archetypes
archetype_seeds = {
    "mundane_dread": 42, "occult_sanctum": 100, "liminal_purgatory": 200,
    "body_horror_theatre": 300, "ancient_sanctuary": 400, "cosmic_archive": 500,
    "tech_utopia": 600, "alien_frontier": 700, "void_abyss": 800,
    "domestic_trauma": 900, "glitch_reality": 1000, "conspiracy_bunker": 1100,
    "training_grounds": 1200,
}

lines.append("-- Update atmospheres with generated music definitions")
lines.append("")

for arch, seed in archetype_seeds.items():
    defs = generate_all_states(arch, seed)
    j = json.dumps(defs).replace("'", "''")
    lines.append(f"UPDATE atmospheres SET music_definitions = '{j}', updated_at = NOW()")
    lines.append(f"  WHERE archetype = '{arch}' AND music_definitions IS NULL;")
    lines.append("")

# Training grounds variations
for var_seed in [2001, 2002, 2003]:
    defs = generate_all_states("training_grounds", var_seed)
    j = json.dumps(defs).replace("'", "''")
    lines.append(f"UPDATE atmospheres SET music_definitions = '{j}', updated_at = NOW()")
    lines.append(f"  WHERE archetype = 'training_grounds' AND generator_seed = {var_seed} AND music_definitions IS NULL;")
    lines.append("")

# 2. Boss themes
lines.append("-- Insert boss theme atmospheres")
lines.append("")

boss_configs = [
    ("Boss: Pallid Mask", "body_horror_theatre", 5001),
    ("Boss: Tower Guardian", "cosmic_archive", 5002),
    ("Boss: Void Entity", "void_abyss", 5003),
    ("Boss: Glitch Lord", "glitch_reality", 5004),
    ("Boss: Final Ascent", "tech_utopia", 5005),
]

for name, base_arch, seed in boss_configs:
    params = ARCHETYPES[base_arch]
    boss_defs = {
        "explore": None,
        "combat": generate_state(params, "combat", seed),
        "boss": generate_state(params, "boss", seed + 100),
        "mystery": generate_state(params, "mystery", seed + 200),
    }
    j = json.dumps(boss_defs).replace("'", "''")
    esc_name = name.replace("'", "''")
    lines.append(f"INSERT INTO atmospheres (name, archetype, description, music_definitions, generator_bpm, generator_key, generator_scale, generator_complexity, generator_seed, created_at, updated_at)")
    lines.append(f"  SELECT '{esc_name}', NULL, 'Unique boss theme', '{j}', {params['bpm_range'][0]}, '{params['key']}', '{params['scale']}', 7, {seed}, NOW(), NOW()")
    lines.append(f"  WHERE NOT EXISTS (SELECT 1 FROM atmospheres WHERE name = '{esc_name}');")
    lines.append("")

# 3. Extended SFX set
lines.append("-- Insert extended SFX presets")
lines.append("")

extended_sfx = [
    ("sfx_player_hit", "combat", "Player Damage", "hit", 200, 0.5, 0.0, False),
    ("sfx_dark_ritual", "combat", "Dark Ritual Proc", "death", 300, 0.7, 0.0, False),
    ("sfx_ui_hover", "ui", "Button Hover", "blip", 400, 0.2, 0.0, False),
    ("sfx_ui_error", "ui", "Error/Denied", "error", 500, 0.5, 0.0, False),
    ("sfx_beat_reveal", "narrative", "Beat Reveal", "drop", 600, 0.4, 0.0, False),
    ("sfx_gold", "progression", "Gold Pickup", "blip", 700, 0.3, 0.05, False),
]

for config_key, category, display_name, sfx_cat, seed, vol, pitch, spatial in extended_sfx:
    preset = generate_preset(sfx_cat, seed)
    j = json.dumps(preset).replace("'", "''")
    spatial_str = "true" if spatial else "false"
    lines.append(f"INSERT INTO audio_configs (config_key, category, display_name, preset_definition, base_volume, pitch_variation, spatial_enabled, created_at, updated_at)")
    lines.append(f"  SELECT '{config_key}', '{category}', '{display_name}', '{j}', {vol}, {pitch}, {spatial_str}, NOW(), NOW()")
    lines.append(f"  WHERE NOT EXISTS (SELECT 1 FROM audio_configs WHERE config_key = '{config_key}');")
    lines.append("")

# Write output
output_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "db", "040_seed_music_definitions.sql")
with open(output_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Written {len(lines)} lines to {output_path}")
